env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/outcluster/main.go
    id: "outcluster"
    binary: omain
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - main: ./cmd/incluster/main.go
    id: "incluster"
    binary: imain
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
- image_templates: ["igumus/controller:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  ids:
    - incluster
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/igumus/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/igumus/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["igumus/controller:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  ids:
    - incluster
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/igumus/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/igumus/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: igumus/controller:{{ .Version }}
  image_templates:
  - igumus/controller:{{.Version}}-amd64
  - igumus/controller:{{.Version}}-arm64v8
- name_template: igumus/controller:latest
  image_templates:
  - igumus/controller:{{.Version}}-amd64
  - igumus/controller:{{.Version}}-arm64v8

source:
  enabled: false

changelog:
  skip: true

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    builds:
      - outcluster
    format_overrides:
      - goos: windows
        format: zip
