apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ctr-ns
  name: ctr-ns
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctr
  namespace: ctr-ns
  labels:
    app: ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctr
  template:
    metadata:
      labels:
        app: ctr
    spec:
      containers:
      - image: igumus/controller:1.0.2
        name: controller
      serviceAccountName: ctr-sa