apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctr-cr
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch

--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctr-sa
  namespace: ctr-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctr-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ctr-cr
subjects:
- kind: ServiceAccount
  name: ctr-sa
  namespace: ctr-ns